<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllQuery()
    {
        $queryBuilder = $this->createQueryBuilder('product');
        $queryBuilder->orderBy('product.id', 'desc');

        return $queryBuilder->getQuery();
    }
}
